name: Publish package

on:
  workflow_run:
    workflows: ["Code checks"]
    branches:
      - dev
      - master
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUN_VERSION: 1.2.5

defaults:
  run:
    shell: bash
    working-directory: ./ # Ensure bun install runs in the correct working directory

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Failed workflow
        run: |
          echo "Code checks workflow failed"
          exit 1

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

        with:
          bun-version: ${{ env.BUN_VERSION }}

      # Install dependencies using Bun
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles('**/bun.lock') }}

  publish:
    runs-on: ubuntu-latest
    needs:
      - setup

    permissions:
      contents: write # allow GITHUB_TOKEN to create release
      packages: write # allow GITHUB_TOKEN to publish packages
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles('**/bun.lock') }}

      - name: Set git user
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish RC
        if: github.ref == 'refs/heads/dev'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bunx changelogen --publishTag rc --prerelease --nameSuffix rc --push

      - name: Publish
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bunx changelogen --release --publish --push
